# Generated by Django 5.2 on 2025-04-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingreview',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='parkingbooking',
            name='guest',
        ),
        migrations.DeleteModel(
            name='guest',
        ),
    ]
