# Generated by Django 5.2 on 2025-04-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
