# Generated by Django 5.2 on 2025-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_activity_log_agriculture_api_docs_asana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
