# Generated by Django 5.2 on 2025-04-30 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_booking_customer_review_customer_alter_review_room'),
        ('services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomcleaninglog',
            name='cleaned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'HOUSEKEEPING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.staff'),
        ),
        migrations.AddField(
            model_name='roomcleaninglog',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.room'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(choices=[('laundry', 'Laundry'), ('housekeeping', 'Housekeeping'), ('cleaning', 'Cleaning'), ('delivery', 'Delivery'), ('restaurant', 'Restaurant')], default='laundry', max_length=100),
        ),
    ]
