# Generated by Django 5.2 on 2025-04-29 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
        migrations.RemoveField(
            model_name='review',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='guest',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.RemoveField(
            model_name='roomcleaninglog',
            name='cleaned_by',
        ),
        migrations.RemoveField(
            model_name='roomcleaninglog',
            name='room',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='RoomCleaningLog',
        ),
    ]
